VirtoCommerce.CatalogModule.Data/Services/ItemServiceImpl.cs

I'm in the process of storing products in Azure CosmosDB and it would be very handy to be able to re-use LoadDependencies,  ApplyInheritanceRules and ValidateProducts.

Allow inheriting ItemServiceImpl

---

VirtoCommerce.CatalogModule.Web.Core/Converters/CatalogConverter.cs
VirtoCommerce.CatalogModule.Web.Core/Converters/CategoryConverter.cs
VirtoCommerce.CatalogModule.Web.Core/Converters/ProductConverter.cs

When properties of catalogs, categories and products don't have a property definition, the values are added at end of the list. The user however expects the properties to be ordered alphabetically.

Sort dynamically added properties

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/property-dictionary-list.js
VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js
VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.js
VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.tpl.html

Changes made in `va-platform2` directive for #174:
* `getPropValues` function: added `countToSkip` and `countToTake` parameters. They are used for paged parameter loading.
* Added `loadNextDictionaryValues` method which is called by scrolling dictionary value list down. It loads next page of dictionary values (if the backend has more values to send). It is also used internally by `loadDictionaryValues` method which loads first page of values.
* Added optional `page-size` attribute that is used to adjust page size. If it is not specified, `va-property2` will use `50` as a fallback value.
* Modified templates for lists of dictionary values: replaced hard-coded English placeholders by translatable resource strings from `??.VirtoCommerce.Common.json` resources (located in …

174: added infinite scrolling for dictionary property values

---

VirtoCommerce.CatalogModule.Data/Services/PropertyDictionaryItemService.cs

When searching for all property dictionary items using the propertyDictionaryItemService, it seems that a combination of sorting and paging on the produced EF query returns unstable (duplicate) results.
This behaviour got introduced when an additional sort was added in commit https://github.com/VirtoCommerce/vc-module-catalog/commit/56fb799d
I was able to mitigate the issue by forcing a parameterized query but the root cause why SQL is returning unstable results is unknown to me.
Reproducible by executing the queries in following file and comparing the result sets:
[EFReproductionQueries.zip](https://github.com/delawarePro/vc-module-catalog/files/2892976/EFReproductionQueries.zip)

Force parameterized offset query to fix paging issue.

---

VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs

There are some fields missing for variations when they are loaded with parent products, such as Links.
This change adds the links loading for variations and extracts the logic for loading variations to a separate virtual method for better extensibility.

Extract variations loading to separate virtual method and add links

---

VirtoCommerce.CatalogModule.Web/Module.cs
VirtoCommerce.CatalogModule.Web/module.manifest

Add the new setting Catalog.Search.EventBasedIndexation.Enable  that will allows to  switch on/off  the event-based indexation behavior
https://github.com/VirtoCommerce/vc-module-catalog/issues/288

288 - Allow to disable event-based indexation

---

VirtoCommerce.CatalogModule.Data/Model/ItemEntity.cs

Issue comes when we try to create item in the IItemService.Create() with object which have PropertyValues = null.
Dear colleagues, could you please tell me, why we do not initializing collections in the constructors?

Added checking for null before working with property values

---

VirtoCommerce.CatalogModule.Web.Core/Model/PropertyDictionaryItemSearchResult.cs
VirtoCommerce.CatalogModule.Web.Core/VirtoCommerce.CatalogModule.Web.Core.csproj
VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModulePropertyDictionaryItemsController.cs

The PropertyDictionaryItem search api response type is 'PropertyDictionaryItem[]' not 'PropertyDictionaryItemSearchResult', it causes that autorest client api deserialize json failed.

fix: propertydictionaryitem api response type

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/DynamicAssociationSearchRequestBuilder.cs

Possible we should use OR filter on multiple values of each particular property.

VP-3296: Empty response when admin set several categories for products to display in association

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/editorialReview-detail.js

When I update variation descriptions, they are not saved
Add ability to save inherited review as new for variations.

VP-3246: Add ability to save inherited review as new for variations.

---

src/VirtoCommerce.CatalogModule.Data/Services/AssociationService.cs

Product association isn't removed in Admin after Delete from API
Fix cache clear after delete product association

VP-3596: Fix cache clear after delete product association

---

.github/workflows/synced-main.yml

Changed azure-blob-storage-upload version to master
Added path-ignore for push and PR events

VP-4020: Fix upload blob storage fails

---

src/VirtoCommerce.CatalogModule.Core/ModuleConstants.cs

Setting Catalog.ExposeAliasInDictionary useless and should be removed
Remove setting
Remove setting

VP-3515: Settings -> Catalog -> Add correct name and description to option

---

src/VirtoCommerce.CatalogModule.Data/Services/CategoryService.cs

VP-5638 Error when user import file in Import & Export

VP-5638 Fix category import error

---

src/VirtoCommerce.CatalogModule.BulkActions/Services/BulkPropertyUpdateManager.cs
src/VirtoCommerce.CatalogModule.Core/Model/Property.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/action-edit-properties.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/step-select-properties.tpl.html
tests/VirtoCommerce.CatalogModule.Tests/BulkPropertyUpdateManagerTests.cs

VP-5502 User see only products and variations properties

VP-5502 User see only products and variations properties

---

src/VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.tpl.html

Error when user select LongText-dictionary-multivalue-multilang as property for dynamic association
Add template LongText-dictionary-multivalue-multilang.html

VP-3570: Error when user select LongText-dictionary-multivalue-multilang as property for dynamic association

---

src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs

By inheriting `AssociationEntity` from `Entity` in https://github.com/VirtoCommerce/vc-module-catalog/commit/2a0249ada6c96bec8030ac0147fc885c6c38166e#diff-2d38b26f0e0caee3d2b827a89deadf10dad1ffb852baeb8627b3c75eb56e14c0R9, the result of `CatalogRepositoryImpl.SearchAssociations` was changed - because `Entity.Equals` differs from previous `ValueObject.Equals` based on equality components. `Entity.Equals` uses `Id`, which is the same in query for all items of associated category. Seems while materializing results, EF uses `Equals`, which leads to equality of all association elements in one associated category.
Fixed this problem by generating new Id for every association element inside every associated category.

VP-6015: Fix category associations search

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-asset-list.js

VP-5986 [QA Regression v3] Option"Copy link" not working in products's assets widget
Fix localization label

VP-5986: Copy link does not work

---

src/VirtoCommerce.CatalogModule.Core/Extensions/PropertyExtensions.cs
src/VirtoCommerce.CatalogModule.Core/Model/CatalogProduct.cs
src/VirtoCommerce.CatalogModule.Core/Model/Category.cs
src/VirtoCommerce.CatalogModule.Core/Model/ExcludedProperty.cs
src/VirtoCommerce.CatalogModule.Core/Model/IHasExcludedProperties.cs
src/VirtoCommerce.CatalogModule.Core/Model/Property.cs
src/VirtoCommerce.CatalogModule.Data/Migrations/20201123103844_AddCategoryExcludedProperties.Designer.cs
src/VirtoCommerce.CatalogModule.Data/Migrations/20201123103844_AddCategoryExcludedProperties.cs
src/VirtoCommerce.CatalogModule.Data/Model/CategoryEntity.cs
src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogDbContext.cs

Adds the ability to store excluded property names per category. The excluded properties are then ignored in the inheritance of a category and its products.

Add excluded properties to category

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CatalogDocumentBuilder.cs

VP-6151 /api/catalog/search/products not working for categoryId
Search product API does not work when:
1.  search criteria contain outline field 
2.  any category has upper case letter in the ID field  
because when we create outline filter ( `IFilter CreateOutlineFilter(CatalogIndexedSearchCriteria criteria)`  ) we convert outline to lowercase.
Convert outlines to lowercase before indexing

VP-6151:  search products does not work with outlines in search criteria

---

src/VirtoCommerce.CatalogModule.Data/Services/CategoryMover.cs
src/VirtoCommerce.CatalogModule.Data/Validation/ListEntriesMoveRequestValidator.cs
tests/VirtoCommerce.CatalogModule.Tests/CategoryMoverTests.cs
tests/VirtoCommerce.CatalogModule.Tests/ListEntriesMoveRequestValidatorTests.cs

Moving categories to its children is prohibited now.

VP-6350: Add protection against category hierarchy cycles

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CatalogDocumentBuilder.cs
tests/VirtoCommerce.CatalogModule.Tests/CatalogDocumentBuilderTests.cs

That fixes outline items names search. Item ids used lowercased, but by some mistake, ids for names not.

VP-6051: Fix product indexation bug: search names for outline items

---

src/VirtoCommerce.CatalogModule.Core/Model/Category.cs

VP-6721 Properties/Parent properties of categories with the same name but different PropertyType are considered as same
If a Catalog has defined a Category property and Product property with the same name and same ValueType but different PropertyType they are considered as same when the Category is fetched (ResponseGroup.Full) and therefore only one is returned under Category.Properties (the one with PropertyType.Product).
Remove additional types

VP-6721: Fix category property does not show when exist product property with same name 

---

src/VirtoCommerce.CatalogModule.Core/Model/Search/CatalogSearchCriteria.cs
src/VirtoCommerce.CatalogModule.Data/Search/CatalogSearchService.cs

VP-6852: Set new pricelist assignments are only possible for the first 20 catalogues
We could not use a generic directive for UI scroll because property ObjectIds doesn't work in some *SearchCriteria
Fix search by ObjectIds
Use already existing ObjectIds for added it SearchCriteria the CatalogIds property.

VP-6852 Add infinite scroll for catalog and priselist selectors

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js

Skipping validation for the same name is the property details is opened for edit and the new name = old name

PT-3388 Skip property name validation for itself

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleListEntryController.cs

PT-4230 Fix error. 'api/catalog/listentries' return the wrong total count at keyword searching

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Localizations/ru.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-dimensions.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-dimensions.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/widgets/itemDimensionWidget.js
src/VirtoCommerce.CatalogModule.Web/Scripts/widgets/itemDimensionWidget.tpl.html

Rework units of measurement for the product:
1. Dimension values not copied anymore from package to product;
2. Add **Use from package type** option to evidently set dimensions from the package;
3. Weight/size widget correctly shows data from the product or package depending on the setting.
https://virtocommerce.atlassian.net/browse/PT-4117

PT-4117: Rework units of measurement

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js

Long text can’t exist with dictionary option
https://virtocommerce.atlassian.net/browse/PT-5136

PT-5136: Long text can’t exist with dictionary option

---

src/VirtoCommerce.CatalogModule.Core/ModuleConstants.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogBrowseFiltersController.cs
src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Model/AggregationProperty.cs

Implementation a new setting for Aggregation Size default value. The default value will apply to Size field when the user adds a new property in "Filtering properties" blade.
https://virtocommerce.atlassian.net/browse/PT-6005

PT-6005: Inconsistent AggregationSize default value - additional improvements

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/aggregation-properties-details.js

Fix broken price range for new aggregation properties, when open Aggregation properties, add Price ranage, Ex: USD property to facet, click on pencil, try to add any value in range facet.
https://virtocommerce.atlassian.net/browse/PT-8971

PT-8971: Fix broken price range for new aggregation properties

---

src/VirtoCommerce.CatalogModule.Data/Model/CatalogEntity.cs

fix: Display incorrect date in Created, Modified date for catalog
https://virtocommerce.atlassian.net/browse/PT-9510

PT-96510: Fixs Display incorrect date in Created, Modified date for catalog

---

src/VirtoCommerce.CatalogModule.BulkActions/DataSources/BaseDataSource.cs
src/VirtoCommerce.CatalogModule.BulkActions/DataSources/DataSourceFactory.cs
src/VirtoCommerce.CatalogModule.BulkActions/DataSources/ProductDataSource.cs
src/VirtoCommerce.CatalogModule.BulkActions/Services/BulkPropertyUpdateManager.cs
tests/VirtoCommerce.CatalogModule.Tests/BaseDataSourceTests.cs
tests/VirtoCommerce.CatalogModule.Tests/ClassCtorTests.cs
tests/VirtoCommerce.CatalogModule.Tests/DataSourceFactoryTests.cs

use IInternalListEntrySearchService instead IListEntrySearchService
remove parent properties for variation product
https://virtocommerce.atlassian.net/browse/PT-9260
https://virtocommerce.atlassian.net/browse/PT-9267

PT-9260 & PT-9267: Fix catalog bulk update functionality

---

src/VirtoCommerce.CatalogModule.Data/Model/ItemEntity.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleListEntryController.cs
tests/VirtoCommerce.CatalogModule.Tests/VirtoCommerce.CatalogModule.Tests.csproj

fix: Properties being emptied on products - Linking and Savin
https://virtocommerce.atlassian.net/browse/PT-10245

PT-10245: Properties being emptied on products - Linking and Saving

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.js

fix:  Deleting a linked category from roots deletes it completely from DB instead of remove link.
https://virtocommerce.atlassian.net/browse/PT-10174

PT-10174:  Deleting a linked category from roots

---

src/VirtoCommerce.CatalogModule.Data.SqlServer/Migrations/20230316134918_FixItemCodeIndex.Designer.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/Migrations/20230316134918_FixItemCodeIndex.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/Readme.md

This PR fixes a bug introduced by https://github.com/VirtoCommerce/vc-module-catalog/pull/455
MySQL and PostgreSQL migrations were correct.
**IMPORTANT**
Before installing this update you should find and fix all duplicates, otherwise platform will not start.
```sql
select CatalogId, Code, count(Id)
from Item
group by CatalogId, Code
having count(Id) > 1
```
https://virtocommerce.atlassian.net/browse/PT-11173

PT-11173: Make index IX_Code_CatalogId unique on SQL Server

---

src/VirtoCommerce.CatalogModule.Core/Search/IProductSearchService.cs
src/VirtoCommerce.CatalogModule.Core/Services/ICatalogService.cs
src/VirtoCommerce.CatalogModule.Core/Services/ICategoryService.cs
src/VirtoCommerce.CatalogModule.Core/Services/IItemService.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CategoryDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/ProductSearchService.cs
src/VirtoCommerce.CatalogModule.Data/Services/CatalogService.cs
src/VirtoCommerce.CatalogModule.Data/Services/CategoryService.cs
src/VirtoCommerce.CatalogModule.Data/Services/ItemService.cs
tests/VirtoCommerce.CatalogModule.Tests/CategoryInheritanceTests.cs
tests/VirtoCommerce.CatalogModule.Tests/ItemServiceUnitTests.cs

The process of indexing products with many variations, properties, and property attributes consumed a lot of memory.
https://virtocommerce.atlassian.net/browse/PT-12168

PT-12168: Reduce memory consumption when indexing products and categories

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleProductsController.cs

The workaround for the performance issue in [CatalogModuleProducts_GetProductByIds ](https://github.com/VirtoCommerce/vc-module-catalog/blob/a5ea494738c69ef696dd0ae6fc63560c4ee97c1b/src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleProductsController.cs#L101-L105) operation has the side effect of missing response type in code model resulting in crippled Swagger spec that states just plain 200, without actual response model:
```json
{
"/api/catalog/products": {
"get": {
"tags": [
"Catalog"
],
"summary": "Gets products by ids",
"operationId": "CatalogModuleProducts_GetProductByIds",
"parameters": "...",         
"responses": {
"200": {
"description": "Success"
},
"401": {
"description": "Unauthorized"
},
"403": {
"description": "Forbidden"
}
},
"security": "..."
}
}
}
``` …

Explicitly state response model for the CatalogModuleProducts_GetProductByIds operation

---

src/VirtoCommerce.CatalogModule.Core/Model/CatalogProduct.cs
src/VirtoCommerce.CatalogModule.Core/Model/Variation.cs

Hi, I encountered an issue when loading reviews on `CatalogProduct`. If product has no reviews it should inherit reviews from it's parent. This however does not happen due to following code in `CatalogProduct.InheritReviews`:
```cs
var isVariation = GetType().IsAssignableFrom(typeof(Variation));
```
The `isVariation` will be `true` for instances of `CatalogProduct`. Meaning every `CatalogProduct` is a `Variation` which is not true. The code should be changed to:
```cs
var isVariation = GetType().IsAssignableTo(typeof(Variation));
```
Other approach would be to implement `InheritReviews` on `Variation` instead of checking for concrete type in parent class:
```cs
// CatalogProduct.cs
protected virtual void InheritReviews(CatalogProduct parentProduct)
{
if (Reviews.IsNullOrEmpty() && …
```

Fix reviews inheritance in catalog product

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductSearchRequestBuilder.cs

fix: If SearchInVariations is false, ProductSearchRequestBuilder doesn't add "is product" filter.
https://virtocommerce.atlassian.net/browse/PT-12772

PT-12772: If SearchInVariations is false, ProductSearchRequestBuilder doesn't add "is product" filter.

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs

To get Main Product and all its variation in one query by `productfamilyid`: 
```
{
products(
storeId:"Electronics"  
filter: "productfamilyid:6e7a31c35c814fb389dc2574aa142b63 status:hidden,visible")
{
totalCount
items
{
id
code
name
}
}
}
```
productFamilyId == mainProductId

PT-13660: add productFamilyId index property

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogBrowseFiltersController.cs

If you want to exclude products with zero price from aggregations, you should add 0 as first range bound:
https://virtocommerce.atlassian.net/browse/PT-12758
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.412.0-pr-704-5c9a.zip

PT-12758: Exclude 0 as lower bound in price facets if first bound is 0

---

src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductSuggestionService.cs
src/VirtoCommerce.CatalogModule.Web/module.manifest

Configuration example for default provider `ElasticAppSearch` and category provider `ElasticSearch8`:
```
{
"Search": {
"Provider": "ElasticAppSearch",
"DocumentScopes": [
{
"DocumentType": "Category",
"Provider": "ElasticSearch8"
}
]
}
}
```
https://virtocommerce.atlassian.net/browse/PT-14218
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.417.0-pr-706-3bf0.zip
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.414.0-pr-706-3d21.zip

PT-14218: Support different search provider for each document type

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModulePropertyDictionaryItemsController.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-dictionary-details.js

remove the 'catalog:create' and 'catalog:delete' permissions for the edit dictionary item action
https://virtocommerce.atlassian.net/browse/VCST-197
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.801.0-pr-717-ca65.zip

VCST-197: remove extra permissions

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/AggregationConverter.cs

fix: Fixed the issue where the price range aggregation property was not being included in the response of the /api/catalog/search/products.
https://virtocommerce.atlassian.net/browse/VCST-881
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.807.0-pr-726-c4a0.zip

VCST-881: PriceRange Aggregation is not functioning as expected.

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/editorialReview-detail.js

When I have a product variation that inherit reviews (descriptions) from the parent, these reviews are editable, but the edits won't get persisted in the database - they get silently dropped without a warning. This behavior is due to the fact that those edited inherited reviews are ignored when mapping `CatalogProduct` to `ItemService` - [there's a filter](https://github.com/VirtoCommerce/vc-module-catalog/blob/f55012d8b82928a681dc1b3d2ef01b44ff818beb/src/VirtoCommerce.CatalogModule.Data/Model/ItemEntity.cs#L356) on `EditorialReview.IsInherited` property.
This PR offers a small change in the UI code, that clears the `isInherited` flag on those editorial reviews that got saved, effectively promoting them to variation's own reviews. In effect, the user can now directly override inherited …

Ensure that saved editorial reviews are not marked as inherited

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/editorialReview-detail.js

fix: Ensure that saved editorial reviews are not marked as inherited (#730)
https://virtocommerce.atlassian.net/browse/VCST-1196
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.810.0-pr-731-93cc.zip

VCST-1196: Ensure that saved editorial reviews are not marked as inherited (#730)

---

src/VirtoCommerce.CatalogModule.Data.MySql/MySqlCatalogRawDatabaseCommand.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/PostgreSqlCatalogRawDatabaseCommand.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/SqlServerCatalogRawDatabaseCommand.cs
src/VirtoCommerce.CatalogModule.Data/Search/ProductAssociationSearchService.cs

feat: Drop the requirement for product associations search criteria to have at least one object id. ProductAssociationSearchCriteria should have at least one ObjectIds or AssociatedObjectIds.
https://virtocommerce.atlassian.net/browse/VCST-1759
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.818.0-pr-741-e1f2.zip

VCST-1759: Drop the requirement for product associations search criteria to have at least one object id

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/ProductAssociationSearchService.cs

fix: Product index document builder fails when a product has an editorial review (description) with a null type or language code.
https://virtocommerce.atlassian.net/browse/VCST-1845
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.819.0-pr-744-c17d.zip

VCST-1845: Indexing fails due to a null reference exception

---

src/VirtoCommerce.CatalogModule.Data.PostgreSql/PostgreSqlCatalogRawDatabaseCommand.cs

fix: Error trying to resolve field associations. column itemid does not exist
https://virtocommerce.atlassian.net/browse/VCST-2253
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.827.0-pr-757-70b5.zip

VCST-2253: Error trying to resolve field associations. column itemid does not exist

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/images.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-asset-list.js

fix: Resolve the issue that the context menu won't disappear after deletion for product assets.
feat: Added confirmation dialog before deleting operation for product asset.
https://virtocommerce.atlassian.net/browse/VCST-2186
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.828.0-pr-756-0c3e.zip

VCST-2186: context menu won't disappear after deletion

---

src/VirtoCommerce.CatalogModule.Web/Content/css/catalog.css

Wrong Padding in Product Gray Box. Increase top padding of .blade-gray-box to 15px. This change will add more space at the top of elements with this class, improving the visual layout and spacing within the user interface.
https://virtocommerce.atlassian.net/browse/VCST-2554
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.835.0-pr-765-ef3d.zip

VCST-2554: Wrong Padding in Product Gray Box

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/AggregationConverter.cs

https://virtocommerce.atlassian.net/browse/VCST-2591
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.844.0-pr-775-5b16.zip

VCST-2591: try localizing outline_named

---

src/VirtoCommerce.CatalogModule.Data/Validation/CategoryPropertyNameValidator.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.tpl.html

fix: Enhance category property validation logic. Added new validation to ensure property uniqueness within categories and consistent property types across the catalog.
https://virtocommerce.atlassian.net/browse/VCST-3176
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.859.0-pr-790-58c9.zip

VCST-3176: Prevent duplicate properties with the same name and type from being added to the category

---

src/VirtoCommerce.CatalogModule.Web/Scripts/directives/itemSearch.js

fix: Search field in catalog does not respond to Enter key press
https://virtocommerce.atlassian.net/browse/VCST-3193
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.859.0-pr-792-28ea.zip

VCST-3193: Search field in catalog does not respond to Enter key press

---

src/VirtoCommerce.CatalogModule.Core/Model/CatalogProduct.cs

In the documentation of `ItemResponseGroup`, `ItemAssets` is described as: `With images and assets`.
However, in the `CatalogProduct.ReduceDetails` function, only the `Assets` field is set to null if this flag is not present.
In this pull request, a line is added to also set the `Images` field to null if the `ItemAssets` flag is not set. This ensures that the functionality more closely matches the documentation.

Fix images not cleared in CatalogProduct.ReduceDetails
