VirtoCommerce.CatalogModule.Data/Converters/PropertyValueConverter.cs
VirtoCommerce.CatalogModule.Web/Scripts/blades/property-valueType.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.tpl.html

This pull request goes together with the one I made for the vc-module-core repository. Note that this change can't be built without it.
Since the data model already supports Integer as value type for dynamic properties, I propose supporting it in the front-end as well.

Add support for Integer Dynamic Property Value Type.

---

VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
VirtoCommerce.CatalogModule.Web/Scripts/blades/property-dictionary.js
VirtoCommerce.CatalogModule.Web/Scripts/blades/property-dictionary.tpl.html
VirtoCommerce.CatalogModule.Web/module.manifest

The Alias functionality is already supported in the backend. This is just an exposure of it through front-end.

Expose DictionaryProperty Alias in front-end

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/blades/common/catalog-items-select.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/blades/item-associations-list.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/blades/item-variation-list.tpl.html

twitching icons

---

VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs
VirtoCommerce.CatalogModule.Test/VirtoCommerce.CatalogModule.Test.csproj

Related to issue VirtoCommerce/vc-platform#1258

Extend CatalogRepositoryImpl with additional constructor

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/common/catalog-items-select.js

Pull the latest dev version of Platform before testing.

Search from Catalog level on catalog product search blade

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-add.js
VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-add.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/catalog.js

Enables to register available product types dynamically.

itemTypesResolverService added

---

VirtoCommerce.CatalogModule.Data/Search/CategorySearchRequestBuilder.cs
VirtoCommerce.CatalogModule.Data/Search/ProductSearchRequestBuilder.cs

VirtoCommerce/vc-module-core#69
IMPORTANT: Need to update VirtoCommerce.Domain nuget package before merging this PR. Otherwise build will fail because of missing field in search criteria

Added fuzzy search support to request builders

---

VirtoCommerce.CatalogModule.Data/Search/Indexing/CatalogDocumentBuilder.cs

indexing integer type too

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/common/catalog-items-select.js
VirtoCommerce.CatalogModule.Web/Scripts/blades/common/catalog-items-select.tpl.html

This will allow to provide a function that will determine whether the catalog item can be selected

Support for custom isItemSelectable function

---

VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs

- Added dictionary items and values loading for variation properties to fix export;

#204 Variation dictionary properties are not restored correctly after import/export:

---

VirtoCommerce.CatalogModule.Web/Model/ListEntry.cs
VirtoCommerce.CatalogModule.Web/Model/ListEntryCategory.cs
VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.js

fix Can't browse found category

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/aggregation-properties-list.js

Refreshing parent blade is updating store data include dynamic properties

FilteredBrowsing property should be updated 

---

VirtoCommerce.CatalogModule.Web/module.manifest

added 
"catalog:BrowseFilters:Read"
"catalog:BrowseFilters:Update"

add permission

---

VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.js

prepare dictionary values before comparison

fix Dictionary values are always dirty

---

VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
VirtoCommerce.CatalogModule.Web/Localizations/ru.VirtoCommerce.Catalog.json
VirtoCommerce.CatalogModule.Web/Scripts/blades/item-variation-list.tpl.html

dev add Manufacturer part number

---

VirtoCommerce.CatalogModule.Web.Core/Converters/CategoryConverter.cs
VirtoCommerce.CatalogModule.Web.Core/Model/Category.cs

Previously Catalog web model was too concrete. 
Abstracted catalog out like Product web model was

Abstracted category out.

---

VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs
VirtoCommerce.CatalogModule.Data/Services/CatalogSearchServiceImpl.cs

check if SeoUrlKeyword is exist

fix Invalid object name 'SeoUrlKeyword'

---

VirtoCommerce.CatalogModule.Web/Content/css/catalog.css
VirtoCommerce.CatalogModule.Web/Scripts/blades/catalogs-list.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/blades/common/catalog-items-select.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/directives/itemSearch.tpl.html

changed blade search panel to general style

---

VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleListEntryController.cs

do not throw exception when category is not specified

do not throw exception when category is not specified

---

VirtoCommerce.CatalogModule.Data/Security/CatalogExportSecurityHandler.cs
VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
VirtoCommerce.CatalogModule.Web/Module.cs

add authorization handler

---

VirtoCommerce.CatalogModule.Data/Extensions/CatalogExportExtensions.cs
VirtoCommerce.CatalogModule.Web/ExportImport/CatalogExportImport.cs

Fixed error on export if no image found

VP-475: Fixed error on export if no image found

---

VirtoCommerce.CatalogModule.Data/BulkUpdate/Model/BulkUpdateActionResult.cs
VirtoCommerce.CatalogModule.Data/BulkUpdate/Model/ChangeCategoryBulkUpdateAction.cs
VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj

add change category action

---

VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json

fix vp-511 Problem with title of screen

---

VirtoCommerce.CatalogModule.Data/BulkUpdate/Services/BulkUpdatePropertyManager.cs
VirtoCommerce.CatalogModule.Web/Scripts/blades/bulk/action-edit-properties.js
VirtoCommerce.CatalogModule.Web/Scripts/blades/bulk/step-edit-properties.js
VirtoCommerce.CatalogModule.Web/Scripts/blades/bulk/step-edit-properties.tpl.html

UI for product's dictionary properties
send edited properties to backend

vp-421_update_properties_UI

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.js
VirtoCommerce.CatalogModule.Web/Scripts/blades/export/exporter-list.js
VirtoCommerce.CatalogModule.Web/Scripts/catalog.js

use isAllSelected and isAnyFilterApplied

vp_525_Remove_inconsistencies_in_catalog_export

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Localizations/ru.VirtoCommerce.Catalog.json

https://virtocommerce.atlassian.net/browse/VP-607

#vp607 catalog localization fix

---

src/VirtoCommerce.CatalogModule.Data/Services/SeoBySlugResolver.cs

add caching to SeoBySlugResolver

add caching to SeoBySlugResolver

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/blades/property-dictionary-details.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.tpl.html

FE: Replacing the Flags as label for culture name label to the culture names.

---

VirtoCommerce.CatalogModule.Data/BulkUpdate/Model/Actions/UpdateProperties/BulkUpdatePropertyManager.cs

remove dictionary property instead change value when updating

vp-617_fix_brand_property_not_updated

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/images-add.js
VirtoCommerce.CatalogModule.Web/Scripts/blades/images-add.tpl.html

for https://github.com/VirtoCommerce/vc-module-catalog/issues/279

add ability to use image url directly without upload

---

VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
VirtoCommerce.CatalogModule.Web/Scripts/blades/images-add.js
VirtoCommerce.CatalogModule.Web/Scripts/blades/images-add.tpl.html

for https://github.com/VirtoCommerce/vc-module-catalog/issues/279

image url as product image(UX improvement)

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-dictionary-details.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.tpl.html

for https://github.com/VirtoCommerce/vc-module-catalog/issues/250

change flags for culture names

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js

Fix saving to local storage user properties filter.

vp-1193 Fix saving to local storege user properties filter

---

VirtoCommerce.CatalogModule.Web/Scripts/blades/item-variation-list.js
VirtoCommerce.CatalogModule.Web/Scripts/widgets/itemVariationWidget.js

fix for https://github.com/VirtoCommerce/vc-module-catalog/issues/299

change visibility of disabled variations

---

VirtoCommerce.CatalogModule.Web/Content/css/catalog.css
VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/blades/property-dictionary-details.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/directives/dictionaryValue.tpl.html
VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.tpl.html

for https://github.com/VirtoCommerce/vc-module-catalog/issues/250

update culture name labels

---

src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CatalogIndexedSearchService.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CategoryIndexedSearchService.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductIndexedSearchService.cs
src/VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
src/VirtoCommerce.CatalogModule.Web/Module.cs

Use searchRequestBuildersRegistrar for override existing request builders
Have to be merged after https://github.com/VirtoCommerce/vc-module-search/pull/12

VP-1419 migrate CatalogPersonalization module to V3

---

VirtoCommerce.CatalogModule.Data/Search/Indexing/CategoryDocumentBuilder.cs

look at https://github.com/VirtoCommerce/vc-module-catalog/pull/303#discussion_r361294494

VP-784 remove Parents from index search

---

VirtoCommerce.CatalogModule.Data/Search/CategorySearchRequestBuilder.cs
VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
VirtoCommerce.CatalogModule.Data/packages.config
VirtoCommerce.CatalogModule.Test/VirtoCommerce.CatalogModule.Test.csproj
VirtoCommerce.CatalogModule.Test/packages.config
VirtoCommerce.CatalogModule.Web.Core/VirtoCommerce.CatalogModule.Web.Core.csproj
VirtoCommerce.CatalogModule.Web.Core/packages.config
VirtoCommerce.CatalogModule.Web/VirtoCommerce.CatalogModule.Web.csproj
VirtoCommerce.CatalogModule.Web/module.manifest
VirtoCommerce.CatalogModule.Web/packages.config

Add terms filter for category visibility status

VP-1667: Hide inactive category

---

VirtoCommerce.CatalogModule.Data/Search/CategorySearchRequestBuilder.cs

Apply UseRelevanceSorting field to skip default sorting parameters

VP-1669: Search not finding category

---

VirtoCommerce.CatalogModule.Data/Search/ProductSearchRequestBuilder.cs

Clear sorting fields if asked relevance sorting

VP-1669 Relevance sorting for product search

---

src/VirtoCommerce.CatalogModule.Core/Model/Category.cs

VP-1583: Add Category.Path setter

---

src/VirtoCommerce.CatalogModule.Core/Model/AssetBase.cs
src/VirtoCommerce.CatalogModule.Data/ExportImport/CatalogExportImport.cs
src/VirtoCommerce.CatalogModule.Data/ExportImport2/ProductExportPagedDataSource.cs

Stop export images for categories when exporting product.

VP-1762: Stop export images referenced by external link.

---

src/VirtoCommerce.CatalogModule.Data/Model/CategoryRelationEntity.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleListEntryController.cs

VP-1754: Unable to delete linked category

---

src/VirtoCommerce.CatalogModule.Data/Validation/PropertyValidator.cs
src/VirtoCommerce.CatalogModule.Web/Content/css/catalog.css
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.tpl.html

Disable dictionary, multi language, multi value UI elements for dictionary property
Add additional validation for properties before save.

VP-1709 VP-1710: Error when turn on dictionary for boolean property

---

src/VirtoCommerce.CatalogModule.Core/Model/Property.cs

VP-1755: Add missing field to converter

VP-1755: Hidden properties are shown on storefront

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js

VP-1709: Disable multivalue switcher for integer type

VP-1709: Error when switch on the Multilanguage for integers

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleCatalogsController.cs

VP-2083 Fix issue with not applying catalogue restriction for user

VP-2083 Fix issue with not applying catalog restriction for user

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/images.js

VP-2137 Check assets permission before enabling the toolbar button

VP-2137 Check assets permission before enabling toolbar button

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleCatalogsController.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/catalogs-select.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/common/catalog-items-select.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-associations-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/selectors/catalog-selector.js
src/VirtoCommerce.CatalogModule.Web/Scripts/widgets/dashboard.js

Change search criteria to get all catalogues and reduce response group.

VP-2065 Fix price blade error when in platform registered more than 20 catalogs

---

src/VirtoCommerce.CatalogModule.Web/Authorization/CatalogAuthorizationHandler.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModulePropertyDictionaryItemsController.cs

Add authorization handler for PropertyDictionaryItemSearchCriteria

VP-2145 Fix permission error when displaying properties

---

src/VirtoCommerce.CatalogModule.Core/Model/Search/CategorySearchCriteria.cs
src/VirtoCommerce.CatalogModule.Data/Search/CategorySearchService.cs

Add ability to search category in root of catalog

VP-2258 Add ability to search category in root of catalog

---

src/VirtoCommerce.CatalogModule.Core/ModuleConstants.cs
src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/VP-2149

Register EventBasedIndexation setting and remove ExposeAliasInDictionary #VP-2149

---

src/VirtoCommerce.CatalogModule.Core/ModuleConstants.cs

Temporary workaround for crashing clothing-and-electronics_3_0_0.zip

Readd ExposeAliasInDictionary (prevent sample data import from crash)

---

src/VirtoCommerce.CatalogModule.Data/Handlers/IndexCategoryChangedEventHandler.cs
src/VirtoCommerce.CatalogModule.Data/Handlers/IndexProductChangedEventHandler.cs
src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/VP-2400

Apply EventBasedIndexation setting value immediately #VP-2400

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleAssociationsController.cs

VP-2159: Fix swagger-related issue with delete and search methods for associations

---

src/VirtoCommerce.CatalogModule.Data/Migrations/20200528061450_ChangeAssociationDeleteBehavior.Designer.cs
src/VirtoCommerce.CatalogModule.Data/Migrations/20200528061450_ChangeAssociationDeleteBehavior.cs
src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogDbContext.cs

Change association delete behavior.
Add migration.

VP-2356: Fix error when deleting association

---

src/VirtoCommerce.CatalogModule.Core/Model/Search/DynamicAssociationSearchCriteria.cs
src/VirtoCommerce.CatalogModule.Core/Model/Search/DynamicAssociationSearchResult.cs
src/VirtoCommerce.CatalogModule.Core/Search/IDynamicAssociationSearchService.cs
src/VirtoCommerce.CatalogModule.Core/Services/IDynamicAssociationService.cs
src/VirtoCommerce.CatalogModule.Data/Search/DynamicAssociationSearchService.cs
src/VirtoCommerce.CatalogModule.Data/Services/DynamicAssociationService.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleDynamicAssociationsController.cs
src/VirtoCommerce.CatalogModule.Web/Module.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-detail.tpl.html

Add searchService and service
Add controller
Implement search, save, get

VP-2696 CRUD for rules preview

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleDynamicAssociationsController.cs
src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-detail.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/mainParameters.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/mainParameters.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/resources/dynamicAssociations.js

Feature/VP-2658: main parameters blade

---

src/VirtoCommerce.CatalogModule.Core/Model/DynamicAssociations/Conditions/BlockMatchingRules.cs
src/VirtoCommerce.CatalogModule.Core/Model/DynamicAssociations/Conditions/BlockResultingRules.cs
src/VirtoCommerce.CatalogModule.Core/Model/DynamicAssociations/Conditions/ConditionCategoryIs.cs
src/VirtoCommerce.CatalogModule.Core/Model/DynamicAssociations/Conditions/ConditionPropertyValues.cs
src/VirtoCommerce.CatalogModule.Core/Model/DynamicAssociations/DynamicAssociationEvaluationContext.cs
src/VirtoCommerce.CatalogModule.Core/Model/DynamicAssociations/DynamicAssociationEvaluationContextExtensions.cs
src/VirtoCommerce.CatalogModule.Core/Model/DynamicAssociations/DynamicAssociationRuleTree.cs
src/VirtoCommerce.CatalogModule.Core/Model/DynamicAssociations/DynamicAssociationRuleTreePrototype.cs

VP-2704: Add expressions for the rules

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleDynamicAssociationsController.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-detail.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/resources/categories.js
src/VirtoCommerce.CatalogModule.Web/Scripts/resources/dynamicAssociations.js

Add ability to delete association
Add ability to select category properties to match
Add ability to select category properties to display

VP-2699: main wizard

---

src/VirtoCommerce.CatalogModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VP-3104

VP-3104: Fix logo

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/mainParameters.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/mainParameters.tpl.html

VP-2658: main parameters blade improvement
* Add placeholder for priority
* Add OK Cancel buttons
* Add localisation for delete

VP-2658: main parameters blade improvement

---

src/VirtoCommerce.CatalogModule.Core/Model/DynamicAssociations/Conditions/BlockOutputTuning.cs
src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/outputTuning.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/outputTuning.tpl.html

VP-2474: Add output tuning blade

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociation-viewer.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociation-viewer.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/outputTuning.js
src/VirtoCommerce.CatalogModule.Web/Scripts/resources/dynamicAssociations.js
src/VirtoCommerce.CatalogModule.Web/Scripts/resources/items.js

Add preview blade
Fix output tuning blade issues

VP-2472: Preview product to match

---

src/VirtoCommerce.CatalogModule.Core/Model/DynamicAssociations/Conditions/BlockOutputTuning.cs
src/VirtoCommerce.CatalogModule.Core/Model/DynamicAssociations/DynamicAssociationConditionEvaluationRequest.cs
src/VirtoCommerce.CatalogModule.Data/Services/DynamicAssociationConditionEvaluator.cs
src/VirtoCommerce.CatalogModule.Data/Services/DynamicAssociationConditionSelector.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/dynamicAssociations-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/dynamicAssociations/outputTuning.js

rename  "string SortInfos" to "string Sort"

VP-2474 Fix variable name 

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/step-edit-properties.js
src/VirtoCommerce.CatalogModule.Web/Scripts/resources/categories.js
src/VirtoCommerce.CatalogModule.Web/Scripts/resources/items.js

Extend API endpoints resources

VP-2101: Changes for dynamic product associations

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.tpl.html

Add readonly "id" field to the Product detail blade

VP-3474: Add id to product blade

---

src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs

Fix MS SQL Error - The incoming request has too many parameters. server supports a maximum of 2100 parameters if remove more than 2100 products.

Fix MS SQL Error - The incoming request has too many parameters. 

---

src/VirtoCommerce.CatalogModule.Data/Search/ListEntrySearchService.cs

https://virtocommerce.atlassian.net/browse/VP-4044

VP-4044: Add missing skip+take parameters in Category search

---

src/VirtoCommerce.CatalogModule.Web/Scripts/widgets/catalogEntryImageWidget.tpl.html

https://virtocommerce.atlassian.net/browse/VP-1859

VP-1859 Remove "track by" from widget to prevent duplication key error

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CategorySearchRequestBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductSearchRequestBuilder.cs

based on fix in v2: https://github.com/VirtoCommerce/vc-module-catalog/commit/f867451e9e7c99793a4a0b57a315d358d6e6933d

VP-1713: Ignore sort by "relevance" field

---

src/VirtoCommerce.CatalogModule.Data/ExportImport/CatalogExportImport.cs

https://virtocommerce.atlassian.net/browse/VP-5011

VP-5011: Fix change export sequence

---

src/VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
src/VirtoCommerce.CatalogModule.Web/Module.cs
src/VirtoCommerce.CatalogModule.Web/module.manifest

#VP-4052 add restrict select data for catalog in ExportNew

---

src/VirtoCommerce.CatalogModule.Data/Migrations/20201008132555_RemoveOrphanCatalogEntities.Designer.cs
src/VirtoCommerce.CatalogModule.Data/Migrations/20201008132555_RemoveOrphanCatalogEntities.cs

+ Remove orphan CatalogImage and CatalogSeoInfo entities that could prevent export.

VP-5473: Add Cascade deletion to CatalogImages

---

src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs
src/VirtoCommerce.CatalogModule.Data/Repositories/ICatalogRepository.cs
src/VirtoCommerce.CatalogModule.Data/Services/CatalogSeoDuplicatesDetector.cs

VP-5334: Call ClearCache before publish event

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-asset-add.tpl.html

VP-4146: Fix translation label

---

src/VirtoCommerce.CatalogModule.Data/Model/ItemEntity.cs

VP-6117 Some fields are not presented in the import mappings
OuterId does not saved when update existing product 
Add outerId to Path method.

VP-6117: Some fields are not presented in the import mappings

---

src/VirtoCommerce.CatalogModule.Data/Migrations/20201125141337_AddCodeCatalogIndex.Designer.cs
src/VirtoCommerce.CatalogModule.Data/Migrations/20201125141337_AddCodeCatalogIndex.cs
src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogDbContext.cs

https://virtocommerce.atlassian.net/browse/VP-6124

#VP-6124 add code and catalogId index

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CatalogDocumentBuilder.cs

VP-6151: Fix sonar issue

---

src/VirtoCommerce.CatalogModule.Web/Content/css/catalog.css
src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Localizations/ru.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.tpl.html

VP-6365 Reorder Name/ID flelds inside the Product blade
Reorder fields on product blade

VP-6365: Reorder Name/ID flelds inside the Product blade

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModulePropertyDictionaryItemsController.cs

VP-6494 Type mismatch in the catalog module
Fix return type

VP-6494: Type mismatch in the catalog module

---

src/VirtoCommerce.CatalogModule.Web/Scripts/widgets/aggregationPropertiesWidget.tpl.html

VP-6648: Add icons to widgets inside store settings blade

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-variation-list.js

Use font awesome in the right way

VP-6768: Security section Replace Key icon

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/action-change-category.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/action-edit-properties.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/action-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/aggregation-properties-details.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/aggregation-properties-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/bulk-action-progress.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/catalog-languages.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/editorialReview-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/editorialReviews-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/export/exporter-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/filter-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/images-add.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/images.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-asset-add.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-asset-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-property-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-variation-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-attributes.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-dictionary-details.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-dictionary-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-type.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-validationRules.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/step-edit-properties.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/step-select-properties.js

VP-6864: Fix header icon

---

src/VirtoCommerce.CatalogModule.Core/Model/Search/CatalogSearchCriteria.cs
src/VirtoCommerce.CatalogModule.Data/Search/CatalogSearchService.cs

VP-6852: Set new pricelist assignments are only possible for the first 20 catalogues
Revert changes
Add searching by ObjectIds too

VP-6852: Add search by ObjectIds 

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs

Add Gtin property to index and all to search for products by GTIN.

VP-7126: Add Gtin property to index and all to search products by GTIN

---

src/VirtoCommerce.CatalogModule.Web/Content/css/catalog.css
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/catalog-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/catalog-detail.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/category-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/category-detail.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/virtual-catalog-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/catalog.js
src/VirtoCommerce.CatalogModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VP-7031

VP-7031: Refactor all inputs in catalog, category and item detail blades to register dynamically and render in va-metaform

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-associations-list.js

https://virtocommerce.atlassian.net/browse/PT-27

PT-27: Rebind changed underlying data with ui-grid

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs

https://virtocommerce.atlassian.net/browse/PT-146

PT-473: Fix variation assets indexing

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-selector.js

https://virtocommerce.atlassian.net/browse/PT-669

PT-670: Fix folder icon

---

src/VirtoCommerce.CatalogModule.Web/VirtoCommerce.CatalogModule.Web.csproj

It makes no sense when `IsPackable = false`.

PT-952: Remove redundant options

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/bill-of-materials-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-associations-list.js

https://virtocommerce.atlassian.net/browse/PT-1040

PT-1040 add productType to associations when fetching product details

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.tpl.html

https://virtocommerce.atlassian.net/browse/PT-678
Hide button:
Properties hidden:

PT-679 Add hide empty property values command

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js

https://virtocommerce.atlassian.net/browse/PT-1339

PT-1339 filter properties by type

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js

https://virtocommerce.atlassian.net/browse/PT-1357

PT-1357 hide variation properties same as product properties

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-variation-list.js

https://virtocommerce.atlassian.net/browse/PT-1522

PT-1524 disable Track Inventory for variations of Digital and BoM products

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CategoryDocumentBuilder.cs

https://virtocommerce.atlassian.net/browse/PT-871

PT-872: Inherit "hidden" flag from parent categories

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Localizations/ru.VirtoCommerce.Catalog.json

https://virtocommerce.atlassian.net/browse/PT-1646

PT-1647: Fix localization

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-626

PT-1809: Add localized values for Bulk Actions titles

---

docs/view-product-variations.md

https://virtocommerce.atlassian.net/browse/PT-412

PT-412 updated Variation docs

---

src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogDbContext.cs

https://virtocommerce.atlassian.net/browse/PT-2029
Changes: https://github.com/VirtoCommerce/vc-module-catalog/pull/510/files?diff=split&w=1#diff-356c65e89cc719e4c309c086a221cdd2403adb777f60aacf006479ae42e572b3R39

PT-2029: Remove internal call to EF Core

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js

https://virtocommerce.atlassian.net/browse/PT-1738

PT-1741: Rename Add property to Add Custom property button

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-asset-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-asset-list.js

https://virtocommerce.atlassian.net/browse/PT-895

PT-895: Get languages from the parent catalog

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js

https://virtocommerce.atlassian.net/browse/PT-2069

PT-2069: Add property button name for catalogs and categories

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js

https://virtocommerce.atlassian.net/browse/PT-2168

PT-2168: Opening Properties Blade

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.js

https://virtocommerce.atlassian.net/browse/PT-2179

PT-2179: Ensure catalog name loaded to breadcrumb

---

src/VirtoCommerce.CatalogModule.Data/ExportImport/CatalogExportImport.cs

https://virtocommerce.atlassian.net/browse/PT-2018

PT-2020 Import save categories fixes

---

src/VirtoCommerce.CatalogModule.Data/ExportImport/CatalogExportImport.cs

Reverts VirtoCommerce/vc-module-catalog#518

Revert "PT-2020 Import save categories fixes"

---

src/VirtoCommerce.CatalogModule.Core/Model/Category.cs
src/VirtoCommerce.CatalogModule.Data/Services/ItemService.cs

https://virtocommerce.atlassian.net/browse/PT-2224

PT-2226 Add SeoInfo to Category in Product.Links

---

src/VirtoCommerce.CatalogModule.Core/Model/OutlinePart/NameOutlinePartResolver.cs

https://virtocommerce.atlassian.net/browse/PT-2232

PT-2233: Fix name resolve for product outline item

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-selector.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/step-select-properties.tpl.html
src/VirtoCommerce.CatalogModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-799

PT-2629: Restyle properties selector

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-validationRules.js

https://virtocommerce.atlassian.net/browse/PT-704

PT-705: Fix Catalog property length validation rules UI

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-validationRules.js

https://virtocommerce.atlassian.net/browse/PT-2734

PT-2734: Ensure property validation rules set and visible in UI

---

src/VirtoCommerce.CatalogModule.Core/ModuleConstants.cs

https://virtocommerce.atlassian.net/browse/PT-164

PT-164: Hide UseSeoDeduplication option from UI

---

.github/workflows/deploy-pr.yml
src/VirtoCommerce.CatalogModule.Core/Model/CategoryPropertyValidationRequest.cs
src/VirtoCommerce.CatalogModule.Core/Model/Search/PropertySearchCriteria.cs
src/VirtoCommerce.CatalogModule.Data/Validation/CategoryPropertyNameValidator.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModulePropertiesController.cs
src/VirtoCommerce.CatalogModule.Web/Module.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/resources/properties.js

PT-1867: Add validation for Property Name for Variation

---

src/VirtoCommerce.CatalogModule.Data/Validation/PropertyValidator.cs

PT-2706: Nice message

---

docs/manage-categories.md

PT-2637 fix broken image links

---

src/VirtoCommerce.CatalogModule.Data/Services/ItemService.cs
src/VirtoCommerce.CatalogModule.Data/Services/PropertyService.cs
src/VirtoCommerce.CatalogModule.Data/Validation/ProductValidator.cs
src/VirtoCommerce.CatalogModule.Web/Module.cs
tests/VirtoCommerce.CatalogModule.Tests/ItemServiceUnitTests.cs
tests/VirtoCommerce.CatalogModule.Tests/PropertyValidatorsTests.cs
tests/VirtoCommerce.CatalogModule.Tests/VirtoCommerce.CatalogModule.Tests.csproj

Add DI for ProductValidator and PropertyValidator.

PT-3380: DI for property and product validators

---

docs/glossary.md
docs/manage-physical-products.md

PT-2635: Fix documents references
https://virtocommerce.atlassian.net/browse/PT-2635

PT-2635: Fix documents references

---

src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CatalogDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CategoryDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/IndexDocumentHelper.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
src/VirtoCommerce.CatalogModule.Web/VirtoCommerce.CatalogModule.Web.csproj

Add IndexDocumentFieldValueType to Document field init

PT-2650 Add mapping by Document Field value type

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleCategoriesController.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleProductsController.cs

Seems there is a bug related to https://virtocommerce.atlassian.net/browse/PT-3718 
https://virtocommerce.atlassian.net/browse/PT-3718

PT-3719: Use abstract factory to create SeoInfo instances

---

src/VirtoCommerce.CatalogModule.BulkActions/VirtoCommerce.CatalogModule.BulkActions.csproj
src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
src/VirtoCommerce.CatalogModule.Web/VirtoCommerce.CatalogModule.Web.csproj
tests/VirtoCommerce.CatalogModule.Tests/VirtoCommerce.CatalogModule.Tests.csproj

Added SonarQubeTestProject property to csproj files

VCI-134: Fix project contains only TEST-code issue

---

src/VirtoCommerce.CatalogModule.Web/Content/css/catalog.css
src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-type-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-type-list.tpl.html

PT-1877 Chagne property creation UI

---

VirtoCommerce.CatalogModule.Data/Search/Indexing/CatalogDocumentBuilder.cs
VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogBrowseFiltersController.cs
VirtoCommerce.CatalogModule.Web/Model/AggregationProperty.cs

PT-4034: Hotfix

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/export/exporter-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/catalog.js

PT-3859: Remove "New" label from Generic export UI

---

src/VirtoCommerce.CatalogModule.BulkActions/VirtoCommerce.CatalogModule.BulkActions.csproj
src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
src/VirtoCommerce.CatalogModule.Web/Scripts/catalog.js
src/VirtoCommerce.CatalogModule.Web/VirtoCommerce.CatalogModule.Web.csproj
src/VirtoCommerce.CatalogModule.Web/module.manifest

Make catalog scope picker as a standard multiple selector
https://virtocommerce.atlassian.net/browse/PT-3496

PT-3497: Make catalog scope picker as a standard multiple selector

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CatalogDocumentBuilder.cs

PT-2563 Index empty value for Boolean property with default 'False'

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/common/catalog-items-select.js

PT-2312: Fix duplicating breadcrumbs after click on first crumb

---

src/VirtoCommerce.CatalogModule.Data/Validation/PropertyValidator.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js

Multivalue properties for Integer types
https://virtocommerce.atlassian.net/browse/PT-4686

fix: integer multivalue

---

src/VirtoCommerce.CatalogModule.Data/Handlers/VideoOwnerChangingEventHandler.cs

PT-5257: Prevent video remove after product save

---

src/VirtoCommerce.CatalogModule.Core/Model/CatalogChangedEntriesAggregate.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentChangesProvider.cs
src/VirtoCommerce.CatalogModule.Data/Services/CatalogService.cs
src/VirtoCommerce.CatalogModule.Data/Services/CategoryService.cs

PT-5268: Delete deleted products from index when indexing by schedule

---

src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs

Store: Aggregation properties issue
https://virtocommerce.atlassian.net/browse/PT-5503

PT-5503: Store: Aggregation properties issue

---

src/VirtoCommerce.CatalogModule.Data/Handlers/LogChangesChangedEventHandler.cs
src/VirtoCommerce.CatalogModule.Data/Handlers/TrackHierarchyChangesEventHandler.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CategoryDocumentChangesProvider.cs
src/VirtoCommerce.CatalogModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/PT-5711 https://virtocommerce.atlassian.net/browse/PT-5711

PT-5711: Index product/category after catalog hierarchy change

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CatalogDocumentBuilder.cs

Custom properties indexing is fixed
https://virtocommerce.atlassian.net/browse/PT-6193

Custom properties indexing is fixed

---

VirtoCommerce.CatalogModule.sln
src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Data/Handlers/IndexCategoryChangedEventHandler.cs
src/VirtoCommerce.CatalogModule.Data/Handlers/IndexProductChangedEventHandler.cs
src/VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
src/VirtoCommerce.CatalogModule.Web/module.manifest

Partial search index update support
https://virtocommerce.atlassian.net/browse/PT-6527

PT-6527: Partial search index update support

---

src/VirtoCommerce.CatalogModule.Core/Model/Search/Indexed/CatalogIndexedSearchCriteria.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CategorySearchRequestBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/FiltersHelper.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductSearchRequestBuilder.cs
src/VirtoCommerce.CatalogModule.Web/Authorization/CatalogAuthorizationHandler.cs

Filter catalog search by permissions
https://virtocommerce.atlassian.net/browse/PT-6607

PT-6607: Filter catalog search by permissions

---

src/VirtoCommerce.CatalogModule.Web/Scripts/catalog.js

Add dimension widget to BOM
https://virtocommerce.atlassian.net/browse/PT-6871

PT-6871: Add dimension widget to BOM

---

src/VirtoCommerce.CatalogModule.Core/ModuleConstants.cs
src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Data/Extensions/EnumConvertExtension.cs
src/VirtoCommerce.CatalogModule.Data/Handlers/IndexProductChangedEventHandler.cs
src/VirtoCommerce.CatalogModule.Data/Handlers/LogChangesChangedEventHandler.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentChangesProvider.cs
src/VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
src/VirtoCommerce.CatalogModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-6646

PT-6646: Variations indexation

---

src/VirtoCommerce.CatalogModule.Web/Scripts/dialogs/deleteCatalog-dialog.tpl.html

Fix catalog delete confirmation
https://virtocommerce.atlassian.net/browse/PT-7212

PT-7212: Fix catalog delete confirmation

---

src/VirtoCommerce.CatalogModule.Data/Services/PropertyService.cs

https://virtocommerce.atlassian.net/browse/PT-7571

PT-7571: fix property service

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json

Fix localization for category description types
https://virtocommerce.atlassian.net/browse/PT-7422

PT-7422: Fix localization for category description types

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/aggregation-properties-details.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/aggregation-properties-details.tpl.html

Aggregation properties editing fix
https://virtocommerce.atlassian.net/browse/PT-7576

PT-7576: Aggregation properties editing fix

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/bill-of-materials-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/widgets/billOfMaterialsWidget.js

https://virtocommerce.atlassian.net/browse/PT-6991

PT-6991: fix adding BoM items

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleAssociationsController.cs

API for getting multiple products associations
https://virtocommerce.atlassian.net/browse/PT-7587 https://virtocommerce.atlassian.net/browse/PT-7857

PT-7587: API for getting multiple products associations

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js

Properties changes check is fixed
https://virtocommerce.atlassian.net/browse/PT-7960

PT-7960: Properties changes check is fixed

---

src/VirtoCommerce.CatalogModule.BulkActions/Services/BulkPropertyUpdateManager.cs

Fix unnecessary nesting in BulkPropertyUpdateManager

Fix unnecessary nesting

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleCategoriesController.cs

fix: instance Category via factory in GetNewCategory

---

src/VirtoCommerce.CatalogModule.Core/Model/ListEntry/ProductListEntry.cs

Outlines are added to the ProductListEntry
https://virtocommerce.atlassian.net/browse/PT-8263

PT-8263: Outlines are added to the ProductListEntry

---

src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs

Getting of catalog properties fix
https://virtocommerce.atlassian.net/browse/PT-7101

PT-7101: Getting of catalog properties fix

---

src/VirtoCommerce.CatalogModule.Web/Model/AggregationProperty.cs

https://virtocommerce.atlassian.net/browse/PT-6005

PT-6005: Inconsistent AggregationSize default value

---

docs/index.md

Changed links in index.md to actual resources

VCI-149: Updated links

---

src/VirtoCommerce.CatalogModule.Core/Model/CatalogProduct.cs

Method TryInheritFrom split
https://virtocommerce.atlassian.net/browse/PT-8757

PT-8757: Method TryInheritFrom split

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json

Add minor localization fixes

---

src/VirtoCommerce.CatalogModule.Data/Model/ItemEntity.cs

Fix patch to save product variation changes
https://virtocommerce.atlassian.net/browse/PT-8915

PT-8915: Fix patch to save product variation changes

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.tpl.html

https://virtocommerce.atlassian.net/browse/VM-869

VM-860: Relax Vendor restrictions (allow Vendor to be organization)

---

src/VirtoCommerce.CatalogModule.Core/Model/ListEntry/CategoryListEntry.cs
src/VirtoCommerce.CatalogModule.Data/Model/CategoryEntity.cs

fix: code smells
https://virtocommerce.atlassian.net/browse/VM-1012

VM-1012: fix code smells

---

src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogDbContext.cs

Fix EF validation runtime warnings
https://virtocommerce.atlassian.net/browse/PT-9152

PT-9152: Fix EF validation runtime warnings

---

src/VirtoCommerce.CatalogModule.Data/Model/CatalogEntity.cs
src/VirtoCommerce.CatalogModule.Data/Model/CategoryEntity.cs
src/VirtoCommerce.CatalogModule.Data/Model/ItemEntity.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js

fix: Could not save multi-value dictionary after modification
https://virtocommerce.atlassian.net/browse/PT-9724

PT-9724: Could not save multi-value dictionary after modification

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/AggregationConverter.cs

- Added OrdinalIgnoreCase comparer to allDictItemsMap in AggregationConverter for fixing lowercase aggregation values.
- Set aggregation item value from dictionary alias.

Set aggregation item value from dictionary alias

---

src/VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.js

fix button "OK" inactive when user delete value in dictionary property in catalog.
https://virtocommerce.atlassian.net/browse/PT-9388

PT-9388: button "OK" inactive when user delete value in dictionary

---

src/VirtoCommerce.CatalogModule.Web/Localizations/ru.VirtoCommerce.Catalog.json

Updated ru localization

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.tpl.html

fix: The button OK does not activate after updating the Decimal multi-value, Integer multi-value properties
https://virtocommerce.atlassian.net/browse/PT-10003

PT-10003: The button OK does not activate

---

src/VirtoCommerce.CatalogModule.Core/ModuleConstants.cs

fix: UseSeoDeduplication property is missing in AllSettings.

PT-10110: UseSeoDeduplication property is missing in AllSettings.

---

src/VirtoCommerce.CatalogModule.Core/Model/TreeNode.cs
src/VirtoCommerce.CatalogModule.Core/Services/ICategoryTreeService.cs
src/VirtoCommerce.CatalogModule.Data/Services/CategoryTreeService.cs
src/VirtoCommerce.CatalogModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/PT-9956

PT-9956: Add CategoryTreeService

---

src/VirtoCommerce.CatalogModule.Web/Localizations/de.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Localizations/ru.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/catalogs-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/common/catalog-items-select.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/links-list/catalog-items-select-links.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js

https://virtocommerce.atlassian.net/browse/PT-9486
https://virtocommerce.atlassian.net/browse/PT-9539

PT-9486, PT-9539: restrict Decimal multi-language property & remove virtual catalog name encoding

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CategoryDocumentChangesProvider.cs

https://virtocommerce.atlassian.net/browse/PT-9674

PT-9674: category index error fix

---

src/VirtoCommerce.CatalogModule.Data.MySql/MySqlCatalogRawDatabaseCommand.cs

Implemented mysql provider for Catalog module. 
It was tested with mysql 5.7

Catalog mysql provider

---

src/VirtoCommerce.CatalogModule.Data.PostgreSql/PostgreSqlCatalogRawDatabaseCommand.cs

Fix RAW SQL commands for PostgreSql.

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/AggregationConverter.cs

feat: Improve performance for PreFilterOutlineAggregation
https://virtocommerce.atlassian.net/browse/PT-10758

PT-10758: Improve performance for PreFilterOutlineAggregation

---

src/VirtoCommerce.CatalogModule.Data.MySql/MySqlCatalogRawDatabaseCommand.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/PostgreSqlCatalogRawDatabaseCommand.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/SqlServerCatalogRawDatabaseCommand.cs

https://virtocommerce.atlassian.net/browse/PT-11651

PT-11651: Delete linked products before deleting virtual catalog

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/action-edit-properties.js

https://virtocommerce.atlassian.net/browse/PT-9592

PT-9592: add boolean property initialization

---

src/VirtoCommerce.CatalogModule.Core/Model/CatalogProduct.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/catalog.js

feat: Add Product availability into Index document
https://virtocommerce.atlassian.net/browse/PT-11722

PT-11722: Add Product availability into Index document

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/AggregationConverter.cs

feat: Returns Custom Aggregations
https://virtocommerce.atlassian.net/browse/PT-12035

PT-12035: Returns Custom Aggregations

---

.editorconfig
VirtoCommerce.CatalogModule.sln.DotSettings
src/VirtoCommerce.CatalogModule.Core/Search/Indexed/IProductSuggestionService.cs
src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductSuggestionService.cs
src/VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleIndexedSearchController.cs
src/VirtoCommerce.CatalogModule.Web/Module.cs
src/VirtoCommerce.CatalogModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-11848

PT-11848: Add product suggestions

---

src/VirtoCommerce.CatalogModule.Core/Model/Search/Indexed/ProductSuggestionRequest.cs
src/VirtoCommerce.CatalogModule.Core/Search/Indexed/IProductSuggestionService.cs
src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductSuggestionService.cs
src/VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleIndexedSearchController.cs
src/VirtoCommerce.CatalogModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-11860

PT-11860: Index Product name as a suggestable field

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleCatalogsController.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleCategoriesController.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleListEntryController.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleProductsController.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModulePropertiesController.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModulePropertyDictionaryItemsController.cs

fix: Rest API returns Unauthorized instead of Forbid.
https://virtocommerce.atlassian.net/browse/PT-12269

PT-12269: Rest API returns Unauthorized instead of Forbid.

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs

PT-12391: Add description index document fields

---

src/VirtoCommerce.CatalogModule.Core/Model/CatalogLanguage.cs
src/VirtoCommerce.CatalogModule.Data.MySql/Migrations/20230706092526_AddCatalogLanguagePriority.Designer.cs
src/VirtoCommerce.CatalogModule.Data.MySql/Migrations/20230706092526_AddCatalogLanguagePriority.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/Migrations/20230706092608_AddCatalogLanguagePriority.Designer.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/Migrations/20230706092608_AddCatalogLanguagePriority.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/Migrations/CatalogDbContextModelSnapshot.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/Migrations/20230703134923_AddCatalogLanguagePriority.Designer.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/Migrations/20230703134923_AddCatalogLanguagePriority.cs
src/VirtoCommerce.CatalogModule.Data/Model/CatalogLanguageEntity.cs
src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/catalog-languages.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/catalog-languages.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/widgets/catalogPropertyWidget.js
src/VirtoCommerce.CatalogModule.Web/Scripts/widgets/categoryPropertyWidget.js
src/VirtoCommerce.CatalogModule.Web/Scripts/widgets/itemPropertyWidget.js
src/VirtoCommerce.CatalogModule.Web/package-lock.json

https://virtocommerce.atlassian.net/browse/PT-11674

PT-11674: add catalog language sort

---

samples/VirtoCommerce.CatalogModule2.Web/Search/Indexing/CategoryDocumentBuilder.cs
samples/VirtoCommerce.CatalogModule2.Web/Search/Indexing/ProductDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Core/Model/Search/PropertySearchCriteria.cs
src/VirtoCommerce.CatalogModule.Core/Search/SearchServiceExtensions.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CatalogDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CategoryDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/PropertySearchService.cs
tests/VirtoCommerce.CatalogModule.Tests/CatalogDocumentBuilderTests.cs

https://virtocommerce.atlassian.net/browse/PT-11306

PT-11306: Implement IIndexSchemaBuilder

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/CategorySearchRequestBuilder.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductSearchRequestBuilder.cs

https://virtocommerce.atlassian.net/browse/PT-13117

PT-13117: Fix search criteria corruption

---

samples/VirtoCommerce.CatalogModule2.Web/Search/PropertyDictionaryItemSearchService.cs
samples/VirtoCommerce.CatalogModule2.Web/Services/PropertyDictionaryItemService.cs
src/VirtoCommerce.CatalogModule.Core/Events/PropertyDictionaryItemChangedEvent.cs
src/VirtoCommerce.CatalogModule.Core/Events/PropertyDictionaryItemChangingEvent.cs
src/VirtoCommerce.CatalogModule.Core/Search/IPropertyDictionaryItemSearchService.cs
src/VirtoCommerce.CatalogModule.Core/Services/IPropertyDictionaryItemService.cs
src/VirtoCommerce.CatalogModule.Data/ExportImport/CatalogExportImport.cs
src/VirtoCommerce.CatalogModule.Data/ExportImport2/PropertyDictionaryItemExportPagedDataSource.cs
src/VirtoCommerce.CatalogModule.Data/Model/PropertyDictionaryItemEntity.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/AggregationConverter.cs
src/VirtoCommerce.CatalogModule.Data/Search/PropertyDictionaryItemSearchService.cs
src/VirtoCommerce.CatalogModule.Data/Services/PropertyDictionaryItemService.cs
src/VirtoCommerce.CatalogModule.Data/Services/PropertyValuesMapper.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogBrowseFiltersController.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModulePropertiesController.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModulePropertyDictionaryItemsController.cs
tests/VirtoCommerce.CatalogModule.Tests/PropertyDictionaryItemTest.cs

https://virtocommerce.atlassian.net/browse/PT-12561

PT-12561: migrate PropertyDictionaryItemSearchService to CRUD

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs

- Virtualize product status indexing in ProductDocumentBuilder

Virtualize product status indexing

---

src/VirtoCommerce.CatalogModule.Data/Search/BrowseFilters/BrowseFilterService.cs

https://virtocommerce.atlassian.net/browse/PT-13875

PT-13875: load full store in catalog filters to fix entity collections overwrite

---

src/VirtoCommerce.CatalogModule.BulkActions/Services/BulkPropertyUpdateManager.cs
src/VirtoCommerce.CatalogModule.Data/Services/PropertyUpdateManager.cs

https://virtocommerce.atlassian.net/browse/PT-13796

PT-13796: Fix bulk property update

---

src/VirtoCommerce.CatalogModule.Web/Scripts/filters/thumbnail.js
src/VirtoCommerce.CatalogModule.Web/package-lock.json

fix: JavaScript Error Cannot read properties of null (reading replace) if pass null to thumbnail filter
https://virtocommerce.atlassian.net/browse/PT-14301
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.413.0-pr-705-b170.zip

PT-14301: JavaScript Error Cannot read properties of null reading replace

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/action-list.tpl.html

fix: Catalog Bulk Actions are sorted randomly. 
https://virtocommerce.atlassian.net/browse/PT-14315
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.414.0-pr-707-75c8.zip

PT-14315: Catalog Bulk Actions are sorted randomly

---

src/VirtoCommerce.CatalogModule.Data/Services/PropertyUpdateManager.cs

https://virtocommerce.atlassian.net/browse/PT-14035
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.415.0-pr-709-007d.zip

PT-14035: update custom property by name if Id is null (Product partial update)

---

src/VirtoCommerce.CatalogModule.Core/ModuleConstants.cs
src/VirtoCommerce.CatalogModule.Data/Authorization/CatalogAuthorizationRequirement.cs
src/VirtoCommerce.CatalogModule.Data/Authorization/CustomPropertyRequirement.cs
src/VirtoCommerce.CatalogModule.Data/Search/ProductSearchService.cs
src/VirtoCommerce.CatalogModule.Web/Authorization/CatalogAuthorizationHandler.cs
src/VirtoCommerce.CatalogModule.Web/Authorization/CustomPropertyRequirementHandler.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleProductsController.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModulePropertiesController.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModulePropertyDictionaryItemsController.cs
src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Module.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-detail.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/directives/dictionaryValue.tpl.html

https://virtocommerce.atlassian.net/browse/PT-14717
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.424.0-pr-716-c79f.zip

PT-14717: permissions for properties

---

src/VirtoCommerce.CatalogModule.Core/Model/Export/ExportableProduct.cs
src/VirtoCommerce.CatalogModule.Core/Model/Export/TabularProduct.cs
src/VirtoCommerce.CatalogModule.Data/ExportImport2/ProductExportPagedDataSource.cs

https://virtocommerce.atlassian.net/browse/VCST-839
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.805.0-pr-722-49f0.zip

VCST-839: fix: Make ImageUrl exportable

---

src/VirtoCommerce.CatalogModule.Data.SqlServer/SqlServerCatalogRawDatabaseCommand.cs

https://virtocommerce.atlassian.net/browse/VCST-680
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.806.0-pr-723-02c9.zip

VCST-680: fix Association query

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/bill-of-materials-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/catalogs-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/common/catalog-items-select.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-variation-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/links-list/catalog-items-select-links.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/links-list/categories-items-select-links.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/property-dictionary-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/video-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/directives/itemSearch.tpl.html

feat: Remove Counter from Search panel
https://virtocommerce.atlassian.net/browse/VCST-972
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.808.0-pr-727-79a2.zip

VCST-972: Remove Counter from Search panel

---

module.keep
src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Data.PostgreSql/VirtoCommerce.CatalogModule.Data.PostgreSql.csproj
src/VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
src/VirtoCommerce.CatalogModule.Web/Module.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/catalog.js
src/VirtoCommerce.CatalogModule.Web/Scripts/catalogBulkActionsModule.js
src/VirtoCommerce.CatalogModule.Web/module.manifest
tests/VirtoCommerce.CatalogModule.Tests/VirtoCommerce.CatalogModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/VCST-509
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.809.0-pr-728-03e5.zip

VCST-509: optional modules

---

src/VirtoCommerce.CatalogModule.Data/Services/ItemService.cs

fix: Resolves issue with External link encoded after saving
https://virtocommerce.atlassian.net/browse/VCST-1385
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.812.0-pr-732-1b93.zip

VCST-1385: External link encoded after saving

---

src/VirtoCommerce.CatalogModule.Web/Localizations/en.VirtoCommerce.Catalog.json
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/filter-detail.tpl.html

fix: Resolves broken link on new filter blade and improves UX.
https://virtocommerce.atlassian.net/browse/VCST-1523
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.813.0-pr-734-63f0.zip

VCST-1523: Fix broken link on new filter blade.

---

src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs
src/VirtoCommerce.CatalogModule.Data/Services/CatalogService.cs

fix: Improved performance of property value query by applying workaround contains to OPENJSON translation regresses performance https://github.com/dotnet/efcore/issues/32394
https://virtocommerce.atlassian.net/browse/VCST-1610
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.814.0-pr-736-657b.zip

VCST-1610: Improve performance of SQL Query

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs

https://virtocommerce.atlassian.net/browse/VCST-1541
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.815.0-pr-735-9614.zip

VCST-1541: do not index variation as hidden by default

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs

feat: extends product document builder with product dimensions. Weight unit, weight, measure unit, height, width, length
https://virtocommerce.atlassian.net/browse/VCST-1781
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.818.0-pr-743-0031.zip

VCST-1781: Add product dimensions

---

src/VirtoCommerce.CatalogModule.Core/Model/Catalog.cs
src/VirtoCommerce.CatalogModule.Core/Model/CatalogResponseGroup.cs
src/VirtoCommerce.CatalogModule.Data.MySql/Migrations/20241007155027_AddCatalogSeoInfo.Designer.cs
src/VirtoCommerce.CatalogModule.Data.MySql/Migrations/20241007155027_AddCatalogSeoInfo.cs
src/VirtoCommerce.CatalogModule.Data.MySql/Migrations/CatalogDbContextModelSnapshot.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/Migrations/20241007155041_AddCatalogSeoInfo.Designer.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/Migrations/20241007155041_AddCatalogSeoInfo.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/Migrations/CatalogDbContextModelSnapshot.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/Migrations/20241007154900_AddCatalogSeoInfo.Designer.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/Migrations/20241007154900_AddCatalogSeoInfo.cs
src/VirtoCommerce.CatalogModule.Data/Model/CatalogEntity.cs
src/VirtoCommerce.CatalogModule.Data/Model/SeoInfoEntity.cs
src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogDbContext.cs
src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs
src/VirtoCommerce.CatalogModule.Data/Services/CatalogService.cs
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleCatalogsController.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/catalog-detail.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/catalogs-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/catalogs-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/Scripts/catalog.js

* Add Link between SeoInfo and Catalog
* Add UI widget in the admin panel
https://virtocommerce.atlassian.net/browse/VCST-1881
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.823.0-pr-747-57af.zip

VCST-1881: Add SEO info for the catalog

---

src/VirtoCommerce.CatalogModule.Data/Model/ItemEntity.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.js
src/VirtoCommerce.CatalogModule.Web/package-lock.json

fix: The field Pack size take into negative value.
https://virtocommerce.atlassian.net/browse/VCST-2182
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.826.0-pr-752-a5eb.zip

VCST-2182: The field Pack size take into negative value

---

src/VirtoCommerce.CatalogModule.Data.MySql/Migrations/20250130160755_OptionVideoLanguageCode.Designer.cs
src/VirtoCommerce.CatalogModule.Data.MySql/Migrations/20250130160755_OptionVideoLanguageCode.cs
src/VirtoCommerce.CatalogModule.Data.MySql/Migrations/CatalogDbContextModelSnapshot.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/Migrations/20250130160831_OptionVideoLanguageCode.Designer.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/Migrations/20250130160831_OptionVideoLanguageCode.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/Migrations/CatalogDbContextModelSnapshot.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/Migrations/20250130160846_OptionVideoLanguageCode.Designer.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/Migrations/20250130160846_OptionVideoLanguageCode.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/Migrations/CatalogDbContextModelSnapshot.cs
src/VirtoCommerce.CatalogModule.Data/Model/VideoEntity.cs
src/VirtoCommerce.CatalogModule.Data/Search/VideoSearchService.cs

fix: now it possible to save a product video without the language code
https://virtocommerce.atlassian.net/browse/VCST-2600
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.839.0-pr-769-d605.zip

VCST-2600: ability to save a product video without the language code

---

src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogBrowseFiltersController.cs
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/aggregation-properties-details.js
src/VirtoCommerce.CatalogModule.Web/Scripts/blades/aggregation-properties-list.tpl.html
src/VirtoCommerce.CatalogModule.Web/module.manifest
tests/VirtoCommerce.CatalogModule.Tests/VirtoCommerce.CatalogModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/VCST-1812
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.846.0-pr-776-654a.zip

VCST-1812: Open index value mapping from aggregation property details

---

src/VirtoCommerce.CatalogModule.Data/Model/AssetEntity.cs
src/VirtoCommerce.CatalogModule.Data/Model/CatalogLanguageEntity.cs
src/VirtoCommerce.CatalogModule.Data/Model/CategoryDescriptionEntity.cs
src/VirtoCommerce.CatalogModule.Data/Model/EditorialReviewEntity.cs
src/VirtoCommerce.CatalogModule.Data/Model/ImageEntity.cs
src/VirtoCommerce.CatalogModule.Data/Model/PropertyAttributeEntity.cs
src/VirtoCommerce.CatalogModule.Data/Model/PropertyDictionaryValueEntity.cs
src/VirtoCommerce.CatalogModule.Data/Model/PropertyEntity.cs
src/VirtoCommerce.CatalogModule.Data/Model/SeoInfoEntity.cs

This pull request adds the IDataEntity<TEntity, TModel> interface to the entities that already implement all methods in the interface, but do not implement the interface itself.

Add IDataEntity interface to entities that already implement it.

---

src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs

https://virtocommerce.atlassian.net/browse/VCST-2891
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.853.0-pr-784-7055.zip

VCST-2891: load aggregation properties for categoryless products

---

src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs

feat: Enhance full-text indexing with GTIN and MPN fields
https://virtocommerce.atlassian.net/browse/VCST-3054
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.854.0-pr-786-3030.zip

VCST-2945: Enhance full-text indexing with GTIN and MPN fields

---

src/VirtoCommerce.CatalogModule.Core/Extensions/SeoExtensions.cs
src/VirtoCommerce.CatalogModule.Core/Model/ListEntry/CategoryListEntry.cs
src/VirtoCommerce.CatalogModule.Core/Model/ListEntry/ListEntryBase.cs
src/VirtoCommerce.CatalogModule.Core/Model/ListEntry/ProductListEntry.cs

https://virtocommerce.atlassian.net/browse/VCST-2972
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.856.0-pr-789-c1fc.zip

VCST-2972: Add IHasOutlines and IHasRelevanceScore to ListEntryBase

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.js
src/VirtoCommerce.CatalogModule.Web/Scripts/directives/itemSearch.js
src/VirtoCommerce.CatalogModule.Web/Scripts/directives/itemSearch.tpl.html

feat: These changes force to use of relevance sorting when searching by keyword.
https://virtocommerce.atlassian.net/browse/VCST-3157
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.856.0-pr-788-d783.zip

VCST-3157: Enhance search functionality in catalog module

---

src/VirtoCommerce.CatalogModule.Data/Services/BrandSeoResolver.cs

https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.864.0-pr-800-93ec.zip

fix: Avoid loading store multiple times in Brands Seo resolver

---

src/VirtoCommerce.CatalogModule.Data/Services/CatalogSeoResolver.cs
tests/VirtoCommerce.CatalogModule.Tests/CatalogHierarchyHelper.cs
tests/VirtoCommerce.CatalogModule.Tests/CatalogSeoResolverTests.cs

* when product or category for the given language doesn't exist, the item for the default language returns
https://virtocommerce.atlassian.net/browse/VCST-3486
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.869.0-pr-806-4521.zip

VCST-3486: Return seo info for default store language

---

src/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleCategoriesController.cs

Added new REST API endpoint `/api/catalog/categories/batch`
https://virtocommerce.atlassian.net/browse/VCST-3507
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.870.0-pr-807-a470.zip

VCST-3507: Categories batch create-update

---

src/VirtoCommerce.CatalogModule.Data.MySql/MySqlCatalogRawDatabaseCommand.cs
src/VirtoCommerce.CatalogModule.Data.PostgreSql/PostgreSqlCatalogRawDatabaseCommand.cs
src/VirtoCommerce.CatalogModule.Data.SqlServer/SqlServerCatalogRawDatabaseCommand.cs
src/VirtoCommerce.CatalogModule.Data/Extensions/DbContextExtension.cs
src/VirtoCommerce.CatalogModule.Data/Model/CategoryHierarchyItem.cs
src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs
src/VirtoCommerce.CatalogModule.Data/Repositories/ICatalogRawDatabaseCommand.cs

fix: Issues with deleting Catalog with big number of categories can't be deleted.
https://virtocommerce.atlassian.net/browse/VCST-3683
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.880.0-pr-817-e85c.zip

VCST-3683: Catalog with big number of categories can't be deleted

---

Directory.Build.props
src/VirtoCommerce.CatalogModule.Core/VirtoCommerce.CatalogModule.Core.csproj
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/ProductDocumentBuilder.cs
src/VirtoCommerce.CatalogModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VCST-3152
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.882.0-pr-816-6cd5.zip

VCST-3152: Product availability indexing fix

---

samples/VirtoCommerce.CatalogModule2.Web/Search/Indexing/AggregationConverter.cs
src/VirtoCommerce.CatalogModule.Core/Extensions/CategoryExtensions.cs
src/VirtoCommerce.CatalogModule.Data/Search/Indexing/AggregationConverter.cs
tests/VirtoCommerce.CatalogModule.Tests/AggregationRequestBuilderTests.cs

https://virtocommerce.atlassian.net/browse/VCST-3415
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.890.0-alpha.2399-vcst-3415.zip

VCST-3415: Exclude linked categories from facets in collapsed seo links mode

---

src/VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.tpl.html

fix: Filtered Results Display Cut Off
https://virtocommerce.atlassian.net/browse/VCST-4058
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.897.0-pr-837-84f5.zip

VCST-4058: Filtered Results Display Cut Off
